steps:
  - id: 'Instalando go'
    name: 'gcr.io/cloud-builders/go'
    args: ['install', './src']
    env: ['PROJECT_ROOT=soma']

  - id: "Rodando go unit test"
    name: 'gcr.io/cloud-builders/go'
    args: ['test', 'soma', '-v']
    env: ['PROJECT_ROOT=soma']

  - id: "Gerando o build da aplicação"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/phgo', './src']

images: 
  - 'gcr.io/$PROJECT_ID/phgo'