steps:
  - id: 'Instalando go'
    name: 'gcr.io/cloud-builders/go'
    args: ['install', '.']
    env: ['PROJECT_ROOT=src']

  - id: "Rodando go unit test"
    name: 'gcr.io/cloud-builders/go'
    args: ['test', 'soma','-v']
    env: ['PROJECT_ROOT=src']

  - id: "Gerando o build da aplicação"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/phgo', '.']

images: 
  - 'gcr.io/$PROJECT_ID/phgo'